# Generated by Django 4.1 on 2023-10-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_professional_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='local',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='regularteacher',
            name='local',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
