# Generated by Django 4.1 on 2023-10-17 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_professional_local_regularteacher_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'verbose_name': 'Professionel', 'verbose_name_plural': 'Professionels'},
        ),
        migrations.AlterModelOptions(
            name='regularteacher',
            options={'verbose_name': 'Enseignant Généraliste', 'verbose_name_plural': 'Enseignants Généralistes'},
        ),
        migrations.AlterModelOptions(
            name='schooladmin',
            options={'verbose_name': 'Administrateur', 'verbose_name_plural': 'Administrateurs'},
        ),
        migrations.AlterModelOptions(
            name='specialtyteacher',
            options={'verbose_name': 'Enseignant Spécialisé', 'verbose_name_plural': 'Enseignants Spécialisés'},
        ),
    ]
