# Generated by Django 4.1 on 2023-10-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_alter_professional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialtyteacher',
            name='local',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
