# Generated by Django 4.1 on 2022-08-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_options'),
        ('problematiques', '0003_alter_item_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='student',
            field=models.ManyToManyField(blank=True, to='student.student'),
        ),
    ]
