# Generated by Django 4.1 on 2022-08-22 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problematiques', '0004_alter_item_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nom']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='student',
        ),
    ]
