# Generated by Django 4.1 on 2023-09-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='nom',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
