# Generated by Django 4.1 on 2023-09-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='nom',
            field=models.CharField(max_length=10),
        ),
    ]
