# Generated by Django 4.1 on 2023-09-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('school', '0006_alter_group_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='regular_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
    ]
