# Generated by Django 4.1 on 2023-09-29 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_group_regular_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classification'),
        ),
    ]
