# Generated by Django 4.1 on 2023-09-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_group_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='regular_teacher',
        ),
    ]
