# Generated by Django 4.1 on 2023-09-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_group_regular_teacher_group_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='nom',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
