# Generated by Django 4.1 on 2023-09-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_group_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='students',
        ),
    ]
