# Generated by Django 4.1 on 2024-01-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_remove_group_regular_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(max_length=6)),
                ('subject_code', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('visible_to_parents', models.BooleanField()),
                ('mat_2nd', models.CharField(max_length=1)),
            ],
        ),
    ]
