# Generated by Django 4.1 on 2024-01-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_matiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='mat_2nd',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
    ]
