# Generated by Django 4.1 on 2024-01-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_alter_matiere_mat_2nd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='category',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
