# Generated by Django 4.1 on 2024-01-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_matiere_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='subject_code',
            field=models.CharField(max_length=8),
        ),
    ]
