# Generated by Django 4.1 on 2024-01-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_matiere_subject_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='est_enseigne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matiere',
            name='matiere_de_base',
            field=models.BooleanField(default=False),
        ),
    ]
