# Generated by Django 4.1 on 2024-01-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_matiere_est_enseigne_matiere_matiere_de_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEmplois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
