# Generated by Django 4.1 on 2024-01-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_categorieemplois'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('description', models.CharField(default=None, max_length=100, null=True)),
                ('categorie_emplois', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.categorieemplois')),
            ],
        ),
    ]
