# Generated by Django 4.1 on 2024-01-13 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_competence_competencesevaluees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competence',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='competencesevaluees',
            options={'ordering': ['matiere__subject_code', 'competence__nom']},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'ordering': ['est_enseigne', 'subject_code']},
        ),
    ]
