# Generated by Django 4.1 on 2024-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_remove_local_id_alter_local_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='nom',
            new_name='local',
        ),
        migrations.AddField(
            model_name='local',
            name='champ_01',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='champ_02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='conflit_accepte',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='date_maj_hor_cal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='date_maj_hor_cyc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='local',
            name='loc_hors_Eco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='local',
            name='remarque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='local',
            name='capacity',
            field=models.SmallIntegerField(default=0),
        ),
    ]
