# Generated by Django 4.1 on 2024-08-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='matiere',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
