# Generated by Django 4.1 on 2024-08-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_alter_cours_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
