# Generated by Django 4.1 on 2024-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_cours_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
