# Generated by Django 4.1 on 2022-08-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('comite_clinique', models.BooleanField(null=True)),
                ('date_ref_comite_clinique', models.DateField(null=True)),
                ('plan_intervention', models.BooleanField(default=False)),
                ('groupe_repere', models.CharField(max_length=4)),
            ],
        ),
    ]
