# Generated by Django 4.1 on 2022-08-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_comite_clinique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['nom', 'prenom']},
        ),
    ]
