# Generated by Django 4.1 on 2022-08-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_action_statusaction_statusproblematique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problematique',
            old_name='item',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='problematique',
            name='eleve',
        ),
        migrations.AddField(
            model_name='student',
            name='problematiques',
            field=models.ManyToManyField(blank=True, to='student.problematique'),
        ),
    ]
