# Generated by Django 4.1 on 2022-08-22 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0005_rename_item_problematique_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='createur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createur_foreign_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
