# Generated by Django 4.1 on 2022-08-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_action_createur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problematique',
            name='action',
        ),
    ]
