# Generated by Django 4.1 on 2022-08-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_problematique_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='problematiques',
        ),
    ]
