# Generated by Django 4.1 on 2022-08-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_student_problematiques'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='problematique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.problematique'),
        ),
        migrations.AddField(
            model_name='problematique',
            name='eleve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
