# Generated by Django 4.1 on 2022-08-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_action_problematique_problematique_eleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('definition', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.codeetudiant'),
        ),
    ]
