# Generated by Django 4.1 on 2022-08-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_codeetudiant_student_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fiche',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
