# Generated by Django 4.1 on 2022-08-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_fiche'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classification',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
