# Generated by Django 4.1 on 2022-08-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_student_classification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problematique',
            old_name='description',
            new_name='detail',
        ),
        migrations.AlterField(
            model_name='codeetudiant',
            name='definition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
