# Generated by Django 4.1 on 2022-08-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_rename_description_problematique_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problematique',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
