# Generated by Django 4.1 on 2022-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_remove_problematique_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
