# Generated by Django 4.1 on 2022-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_action_detail_alter_action_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
