# Generated by Django 4.1 on 2022-08-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_codeetudiant_definition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeetudiant',
            options={'ordering': ['definition']},
        ),
        migrations.AddField(
            model_name='student',
            name='etat_situation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
