# Generated by Django 4.1 on 2022-08-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problematiques', '0005_alter_item_options_remove_item_student'),
        ('student', '0020_alter_codeetudiant_options_student_etat_situation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problematique',
            unique_together={('nom', 'eleve')},
        ),
    ]
