# Generated by Django 4.1 on 2022-09-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
        ('student', '0024_student_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.classification'),
        ),
    ]
