# Generated by Django 4.1 on 2022-09-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0025_alter_student_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foyer', models.CharField(max_length=4)),
                ('no_fiche', models.CharField(max_length=15)),
                ('nom', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=2)),
                ('plan', models.BooleanField(blank=True, null=True)),
                ('difficulte', models.IntegerField(blank=True, null=True)),
                ('age_30_sept', models.IntegerField(blank=True, null=True)),
                ('note', models.IntegerField(blank=True, null=True)),
                ('matiere', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
