# Generated by Django 4.1 on 2022-09-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='classification',
            field=models.CharField(max_length=4),
        ),
    ]
