# Generated by Django 4.1 on 2022-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0028_grades_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['problematique']},
        ),
        migrations.AlterField(
            model_name='student',
            name='fiche',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('description', 'problematique')},
        ),
    ]
