# Generated by Django 4.1 on 2022-10-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0030_alter_student_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lang',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
