# Generated by Django 4.1 on 2022-10-22 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0031_alter_student_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.codeetudiant'),
        ),
    ]
