# Generated by Django 4.1 on 2023-09-29 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_alter_action_problematique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classification',
        ),
    ]
