# Generated by Django 4.1 on 2023-09-29 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_alter_group_nom'),
        ('student', '0038_remove_student_groupe_repere'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groupe_repere',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.group'),
        ),
    ]
