# Generated by Django 4.1 on 2023-10-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0040_etatdelasituation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='etatdelasituation',
            unique_together=set(),
        ),
    ]
