# Generated by Django 4.1 on 2023-11-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0041_alter_etatdelasituation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fiche',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
